In [2]:
import pandas as pd
df=pd.read_csv(r'E:/Hackethon/Amazon ML Challenge 24/outputs/train_extracted_text_with_embeddings.csv')
df.head()

,Image Name,Extracted Text,BERT_Embedding
0,116R4t6IioL.jpg,"+-4↓ "":'+b",[ 1.55193001e-01 -2.31270231e-02 7.86822736e-...
1,11j0F4QOiFL.jpg,+***,[ 1.00094579e-01 1.54540241e-01 5.92928290e-...
2,1yw53vfQtS.jpg,NaN,NaN
3,21+quvMwZSL.jpg,NaN,NaN
4,21-V2Kx5BVL.jpg,NaN,NaN

In [3]:
import pandas as pd
df=pd.read_csv(r'E:/Hackethon/Amazon ML Challenge 24/outputs/output_paddleocr2.csv')
df.head()

        Image Name Extracted Text
0  116R4t6IioL.jpg     +-4↓ ":'+b
1  11j0F4QOiFL.jpg           +***
2   1yw53vfQtS.jpg            NaN
3  21+quvMwZSL.jpg            NaN
4  21-V2Kx5BVL.jpg            NaN

In [4]:
import pandas as pd
df=pd.read_csv(r'E:/Hackethon/Amazon ML Challenge 24/outputs/train_subset_dataset.csv')
df.head()

,image_link,image_name,image_file,group_id,entity_name,entity_value
0,https://m.media-amazon.com/images/I/61I9XdN6OF...,61I9XdN6OFL,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,748919,item_weight,500.0 gram
1,https://m.media-amazon.com/images/I/71gSRbyXmo...,71gSRbyXmoL,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,916768,item_volume,1.0 cup
2,https://m.media-amazon.com/images/I/61BZ4zrjZX...,61BZ4zrjZXL,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,459516,item_weight,0.709 gram
3,https://m.media-amazon.com/images/I/612mrlqiI4...,612mrlqiI4L,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,459516,item_weight,0.709 gram
4,https://m.media-amazon.com/images/I/617Tl40LOX...,617Tl40LOXL,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,731432,item_weight,1400 milligram

In [6]:
import pandas as pd
df=pd.read_csv(r'E:/Hackethon/Amazon ML Challenge 24/outputs/processed_training_input.csv')
df.head()

,image_link,image_name,image_file,group_id,entity_name,entity_value,Image Name,Extracted Text,training_input
0,https://m.media-amazon.com/images/I/61I9XdN6OF...,61i9xdn6ofl,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,748919,item_weight,500.0 gram,61I9XdN6OFL.jpg,PROP&S AAILL INGRECENT MENAGER 100,item_weight | PROP&S AAILL INGRECENT MENAGER 100
1,https://m.media-amazon.com/images/I/71gSRbyXmo...,71gsrbyxmol,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,916768,item_volume,1.0 cup,71gSRbyXmoL.jpg,TEARRIFIC LEBENSMITTELECHT GEPRAGTES DESIGN AS...,item_volume | TEARRIFIC LEBENSMITTELECHT GEPRA...
2,https://m.media-amazon.com/images/I/61BZ4zrjZX...,61bz4zrjzxl,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,459516,item_weight,0.709 gram,61BZ4zrjZXL.jpg,COMPOSITION Serving Size: 1 Tablet 0.709 gl I ...,item_weight | COMPOSITION Serving Size: 1 Tabl...
3,https://m.media-amazon.com/images/I/612mrlqiI4...,612mrlqii4l,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,459516,item_weight,0.709 gram,612mrlqiI4L.jpg,NaN,item_weight |
4,https://m.media-amazon.com/images/I/617Tl40LOX...,617tl40loxl,E:/Hackethon/Amazon ML Challenge 24/archive/ar...,731432,item_weight,1400 milligram,617Tl40LOXL.jpg,aach HiGH st PSYLLIUM HUSK 1400MG PLANTACQ OVA...,item_weight | aach HiGH st PSYLLIUM HUSK 1400M...

In [9]:
import pandas as pd
df=pd.read_csv(r"E:/Hackethon/Amazon ML Challenge 24/outputs/corrected_file.csv"  )
df

,Unnamed: 0,index,image_link,group_id,entity_name,training_input,entity_value,cleaned_entity_value,corrected_entity_value
0,0,0,https://m.media-amazon.com/images/I/110EibNycl...,156839,height,height,75.0 centimetrerecomm66666666.128 ProductANDin...,75.0 centimetrerecomm,75.0 centimetre
1,1,1,https://m.media-amazon.com/images/I/11TU2clswz...,792578,width,width,100.0 centimetre Product66666666600 volt435rec...,100.0 centimetre,100.0 centimetre
2,2,2,https://m.media-amazon.com/images/I/11TU2clswz...,792578,height,height,50.0 centimetre60666666668 USB0812Z.ANDrecomm5...,50.0 centimetre,50.0 centimetre
3,3,3,https://m.media-amazon.com/images/I/11TU2clswz...,792578,depth,depth,30.0 centimetreAND Product6666666612.60435 USB...,30.0 centimetreAND,30.0 centimetre
4,4,4,https://m.media-amazon.com/images/I/11gHj8dhhr...,792578,depth,depth,10.0 inch66666666AND435 USB Product6012477.850...,10.0 inch,10.0 inch66666666AND435 USB Product6012477.850...
...,...,...,...,...,...,...,...,...,...
131182,131182,131283,https://m.media-amazon.com/images/I/A1rVsIzEtk...,721522,maximum_weight_recommendation,maximum_weight_recommendation,2.6666666666666665 gram ounce ounce6666666660 ...,2.6666666666666665 gram,2.6666666666666665 fluid ounce
131183,131183,131284,https://m.media-amazon.com/images/I/A1rdvZ5zDd...,603688,item_weight,item_weight,200.0 gram1260AND Product043520.66666666 gram ...,200.0 gram,200.0 fluid ounce
131184,131184,131285,https://m.media-amazon.com/images/I/A1rdvZ5zDd...,603688,maximum_weight_recommendation,maximum_weight_recommendation,2.6666666666666665 gram225 gram ounce604356666...,2.6666666666666665 gram,2.6666666666666665 gram225 gram ounce604356666...
131185,131185,131286,https://m.media-amazon.com/images/I/A1tnTUPyr7...,853009,item_weight,item_weight,10.0 gram60AND435 Product USB12. gram671822047760,10.0 gram,10.0 gram60AND435 Product USB12. gram671822047760
131186,131186,131287,https://m.media-amazon.com/images/I/A1tnTUPyr7...,853009,maximum_weight_recommendation,maximum_weight_recommendation,2.6666666666666665 gram ounce ounce66666666 gr...,2.6666666666666665 gram,2.6666666666666665 fluid ounce

In [7]:
import pandas as pd
df=pd.read_csv(r"E:/Hackethon/Amazon ML Challenge 24/archive/student_resource_3/dataset/test.csv"  )
df.head()

,index,image_link,group_id,entity_name
0,0,https://m.media-amazon.com/images/I/110EibNycl...,156839,height
1,1,https://m.media-amazon.com/images/I/11TU2clswz...,792578,width
2,2,https://m.media-amazon.com/images/I/11TU2clswz...,792578,height
3,3,https://m.media-amazon.com/images/I/11TU2clswz...,792578,depth
4,4,https://m.media-amazon.com/images/I/11gHj8dhhr...,792578,depth

In [2]:
# import pandas as pd


# csv_file = r'D:/Amazon ML Challenge 2024/outputs/output_paddleocr1.csv'  
# df = pd.read_csv(csv_file)

# error_text = "OCR_ERROR: 'NoneType' object is not iterable"
# df.iloc[:, 1] = df.iloc[:, 1].replace(error_text, pd.NA)

# output_file = r'D:/Amazon ML Challenge 2024/outputs/output_paddleocr2.csv' 
# df.to_csv(output_file, index=False)

In [3]:
df = df[df['Extracted Text'].isnull()]
df

             Image Name Extracted Text
2        1yw53vfQtS.jpg            NaN
3       21+quvMwZSL.jpg            NaN
4       21-V2Kx5BVL.jpg            NaN
5       21-VzxP3BDL.jpg            NaN
7       211sXYcOHcL.jpg            NaN
...                 ...            ...
255901  caDEyEaRMCm.jpg            NaN
255902  fUyC7fnSnys.jpg            NaN
255903  l8BsJVaKRCe.jpg            NaN
255904  lwd2cSmT2ux.jpg            NaN
255905   mWyQ79S76i.jpg            NaN

[8828 rows x 2 columns]

In [8]:
# Replace NaN with empty strings and convert ALL values to strings
df['Extracted Text'] = df['Extracted Text'].fillna('').astype(str)

# Verify fix
print(df['Extracted Text'].apply(type).unique())  # Should show [<class 'str'>]

[<class 'str'>]

In [9]:
import torch
import pandas as pd
from transformers import BertTokenizer, BertModel
from tqdm import tqdm

def batch_generator(data, batch_size=16):
    """Yield successive batch-sized chunks from data."""
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

def generate_bert_embeddings(df, text_column='Extracted Text', batch_size=16):
    # Clean and convert text data first
    df[text_column] = df[text_column].fillna('').astype(str)
    
    # Set up device and model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased').to(device)
    model.eval()  # Set model to evaluation mode
    
    embeddings = []
    texts = df[text_column].tolist()
    
    with torch.no_grad():
        for batch in tqdm(batch_generator(texts, batch_size), 
                        total=len(texts)//batch_size + 1,
                        desc="Processing batches"):
            # Filter out empty/non-text entries
            valid_texts = [(idx, text) for idx, text in enumerate(batch) if text.strip()]
            
            if not valid_texts:
                embeddings.extend([None] * len(batch))
                continue
                
            # Unpack valid texts and indices
            indices, processed_texts = zip(*valid_texts)
            
            # Tokenize and process batch
            inputs = tokenizer(processed_texts, 
                             return_tensors='pt',
                             padding=True,
                             truncation=True,
                             max_length=512).to(device)
            
            outputs = model(**inputs)
            batch_embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
            
            # Map embeddings back to original batch positions
            batch_results = [None] * len(batch)
            for i, idx in enumerate(indices):
                batch_results[idx] = batch_embeddings[i]
            
            embeddings.extend(batch_results)
    
    return pd.Series(embeddings, index=df.index)

# Usage
df = pd.read_csv(r'D:/Amazon ML Challenge 2024/outputs/output_paddleocr2.csv')
df['BERT_Embedding'] = generate_bert_embeddings(df, 
                                               text_column='Extracted Text',
                                               batch_size=32)  # Adjust based on GPU memory

# Save the extracted text and embeddings to a CSV file
csv_path = r'D:/Amazon ML Challenge 2024/outputs/train_extracted_text_with_embeddings.csv'
df.to_csv(csv_path, index=False)

print(f"Extraction and BERT encoding completed! The results have been saved to {csv_path}")

Processing batches: 100%|██████████| 7998/7998 [14:21<00:00,  9.29it/s]

Extraction and BERT encoding completed! The results have been saved to D:/Amazon ML Challenge 2024/outputs/train_extracted_text_with_embeddings.csv